# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'BloodDonationIOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  pod 'Alamofire'

  target 'BloodDonationIOSTests' do
    inherit! :search_paths
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
  end

end
